cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

egames/urls.py
from django.contrib import admin
from django.urls import path, include
from gamingnews import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('gamingnews/', include('gamingnews.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamingnews/urls.py
from . import views
from django.urls import path

app_name = 'gamingnews'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name="contact"),
    path('game_review/', views.game_review, name="game_review"),
    path('game_detail/<int:id>', views.game_detail, name='game_detail'),
    path('game_search', views.game_result, name='game_result'),
    path('article/', views.article, name="article"),
    path('article_detail/<int:id>', views.article_detail, name="article_detail"),
]

gamingnews/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    cat_name = models.CharField(max_length=200)

    def __str__(self):
        return self.cat_name


class Games(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    price = models.IntegerField()
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='games/')
    vote = models.FloatField(null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='articles/')

    def __str__(self):
        return self.name


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to="user/", blank=True)

    def __str__(self):
        return self.user.username


class Contact(models.Model):
    name = models.CharField(max_length=200, blank=False)
    phone = models.CharField(max_length=20)
    email = models.EmailField(blank=False)
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        db_table = u'Contact'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]


class CartAddProductForm(forms.Form):
    quantity = forms.ChoiceField(choices=PRODUCT_QUANTITY_CHOICES, widget=forms.Select(
        attrs={'class': 'form-control', 'style': 'width: 90px; text-align:center'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

gamingnews/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, Contact



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfileInfo
        exclude = ('user',)


class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=200)
    email = forms.EmailField()
    message = forms.Textarea()

    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message']

gamingnews/views.py
from django.shortcuts import render
from .models import Games, Article
from .forms import *
from django.http import HttpResponse


# Create your views here.
def home(request):
    game_list = Games.objects.order_by('name')
    game_dict = {'games': game_list}
    return render(request, 'gamingnews/home.html', context=game_dict)


def game_detail(request, id=None):
    game = Games.objects.get(pk=id)
    return render(request, 'gamingnews/single-game-review.html', context={"game": game})


def game_review(request):
    game_list = Games.objects.order_by('name')
    game_dict = {'games': game_list}
    return render(request, 'gamingnews/game-review.html', context=game_dict)


def game_result(request):
    game_list = Games.objects.order_by('name')
    game_search = []
    count = 0
    if request.method == "GET":
        games = request.GET.get("games")
        for item in game_list:
            if games.lower() in item.name.lower():
                game_search.append(item)
        if len(game_search) > 0:
            count = len(game_search)
    return render(request, "gamingnews/game-result.html", context={"game_result": game_search, "count": count})


def article(request):
    art = Article.objects.order_by("name")
    games = Games.objects.order_by("name")
    part = int(len(games) / 2)
    lst1 = []
    for i in range(0, part, 1):
        lst1.append(games[i])
    ar = Article.objects.order_by("name")
    part2 = int(len(ar) / 2)
    lst2 = []
    for i in range(0, part2, 1):
        lst2.append(ar[i])
    return render(request, 'gamingnews/post.html', context={'article': art, "games": lst1, "art": lst2})


def article_detail(request, id=None):
    art = Article.objects.get(pk=id)
    gaming = Games.objects.order_by("name")
    part = int(len(gaming) / 2)
    lst1 = []
    for i in range(0, part, 1):
        lst1.append(gaming[i])
    artic = Article.objects.order_by("name")
    part2 = int(len(artic) / 2)
    lst2 = []
    for i in range(0, part2, 1):
        lst2.append(artic[i])
    return render(request, 'gamingnews/single-post.html', context={"article": art, "games": lst1, "art": lst2})


def contact(request):
    registered = False
    if request.method == "POST":
        form_contact = FormContact(data=request.POST)
        if form_contact.is_valid():
            registered = form_contact.save()
            registered.save()
            registered = True
    else:
        form_contact = FormContact()
    response = render(request, 'gamingnews/contact.html', {'contact_form': form_contact, 'registered': registered})
    response.delete_cookie('visit_time')
    return response

templates/gamingnews/contact.html
{% extends "index.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}
    <title>Contact</title>
{% endblock %}

{% block content %}
<!-- ##### Breadcrumb Area Start ##### -->
    <section class="breadcrumb-area bg-img bg-overlay" style="background-image: url({% static 'css_js' %}/img/bg-img/23.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Contact</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-12 col-lg-4">
                            <div class="contact-content mb-100">
                                <a href="#" class="mb-50 d-block"><img src="img/core-img/logo.png" alt=""></a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat.</p>
                            </div>
                        </div>
                        <div class="col-12 col-lg-4">
                            <div class="contact-content mb-100">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat. Aliquam erat volutpat. Sed efficitur diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque.</p>
                            </div>
                        </div>
                        <div class="col-12 col-lg-4">
                            <div class="contact-content mb-100">
                                <!-- Single Contact Info -->
                                <div class="single-contact-info d-flex align-items-center">
                                    <div class="title">
                                        <p>Address</p>
                                    </div>
                                    <p>1481 Creekside Lane Avila Beach, CA 931</p>
                                </div>

                                <!-- Single Contact Info -->
                                <div class="single-contact-info d-flex align-items-center">
                                    <div class="title">
                                        <p>Phone</p>
                                    </div>
                                    <p>+53 345 7953 32453</p>
                                </div>

                                <!-- Single Contact Info -->
                                <div class="single-contact-info d-flex align-items-center">
                                    <div class="title">
                                        <p>E-mail</p>
                                    </div>
                                    <p>yourmail@gmail.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Contact Form Area -->
                <div class="col-12">
                    <h4 class="mb-70">Get In Touch</h4>

                    <!-- Contact Form -->
                    <div class="contact-form-area mb-100">
                           <div class="feedback-form">
                        <div id="contact-response"></div>
                        {% if registered %}
                        <h3>Thanks for contact us</h3>
                        {% else %}
                        <form  method="post" id="contact-form">
                            {% csrf_token %}
                            <fieldset>
                                {% for field in contact_form %}
                                <div class="form-group form-group-fullname">
                                    {{ field.label_tag }}
                                    {% render_field field class="form-control" %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-success" role="alert">{{error|escape}}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                {% endfor %}
                        {% endif %}
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </fieldset>
                        </form>

                    </div>
                    </div>
                </div>

                <div class="col-12">
                    <!-- Google Maps -->
                    <div class="map-area">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22236.40558254599!2d-118.25292394686001!3d34.057682914027104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z4Kay4Ka4IOCmj-CmnuCnjeCmnOCnh-CmsuCnh-CmuCwg4KaV4KeN4Kav4Ka-4Kay4Ka_4Kar4KeL4Kaw4KeN4Kao4Ka_4Kav4Ka84Ka-LCDgpq7gpr7gprDgp43gppXgpr_gpqgg4Kav4KeB4KaV4KeN4Kak4Kaw4Ka-4Ka34KeN4Kaf4KeN4Kaw!5e0!3m2!1sbn!2sbd!4v1532328708137" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->
{% endblock %}

templates/gamingnews/game-result.html
{% extends "index.html" %}
{% load staticfiles %}

{% block title %}
    <title>Game Review</title>
{% endblock %}


{% block content %}
<!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area bg-img bg-overlay" style="background-image: url({% static 'css_js' %}/img/bg-img/27.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Review</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Game Review Area Start ##### -->
    <section class="game-review-area section-padding-100" >
        <div class="container">
             {% if count %}
                <ol><h3>Found {{ count }} games</h3></ol>
             {% endif %}
            <div class="row">
                {% if game_result %}
                <div class="col-12">
                    {% for item in game_result %}
                    <!-- *** Single Review Area *** -->
                    <div class="single-game-review-area d-flex flex-wrap mb-30">
                        <div class="game-thumbnail">
                             <img src="{{ item.image.url }}" alt="" style="width: 390px;height: 245px">
                        </div>
                        <div class="game-content">
                            <span class="game-tag">{{ item.category }}</span>
                            <a href="/gamingnews/game_detail/{{ item.id }}" class="game-title">{{ item.name }}</a>
                            <div class="game-meta">
                                <a href="#" class="game-date">{{ item.updated_at }}</a>
                                <a href="#" class="game-comments">2 Comments</a>
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat. Aliquam erat volutpat. Sed efficitur diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat. Aliquam erat volutpat. Sed efficitur diam.</p>
                            <!-- Download & Rating Area -->
                            <div class="download-rating-area d-flex align-items-center justify-content-between">
                                <div class="download-area">
                                    <a href="#"><img src="{% static 'css_js' %}/img/core-img/app-store.png" alt=""></a>
                                    <a href="#"><img src="{% static 'css_js' %}/img/core-img/google-play.png" alt=""></a>
                                </div>
                                <div class="rating-area text-center">
                                    <h3>{{ item.vote }}</h3>
                                    <div class="stars">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
                    <!-- ### Pagination Area ### -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination mt-100">
                            <li class="page-item active"><a class="page-link" href="#">01</a></li>
                            <li class="page-item"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Game Review Area End ##### -->
{% endblock %}

templates/gamingnews/game-review.html
{% extends "index.html" %}
{% load staticfiles %}

{% block title %}
    <title>Game Review</title>
{% endblock %}


{% block content %}
<!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area bg-img bg-overlay" style="background-image: url({% static 'css_js' %}/img/bg-img/27.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Review</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Game Review Area Start ##### -->
    <section class="game-review-area section-padding-100" >
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% for item in games  %}
                    <!-- *** Single Review Area *** -->
                    <div class="single-game-review-area d-flex flex-wrap mb-30">
                        <div class="game-thumbnail">
                             <img src="{{ item.image.url }}" alt="" style="width: 390px;height: 245px">
                        </div>
                        <div class="game-content">
                            <span class="game-tag">{{ item.category }}</span>
                            <a href="/gamingnews/game_detail/{{ item.id }}" class="game-title">{{ item.name }}</a>
                            <div class="game-meta">
                                <a href="#" class="game-date">{{ item.updated_at }}</a>
                                <a href="#" class="game-comments">2 Comments</a>
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat. Aliquam erat volutpat. Sed efficitur diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris velit arcu, scelerisque dignissim massa quis, mattis facilisis erat. Aliquam erat volutpat. Sed efficitur diam.</p>
                            <!-- Download & Rating Area -->
                            <div class="download-rating-area d-flex align-items-center justify-content-between">
                                <div class="download-area">
                                    <a href="#"><img src="{% static 'css_js' %}/img/core-img/app-store.png" alt=""></a>
                                    <a href="#"><img src="{% static 'css_js' %}/img/core-img/google-play.png" alt=""></a>
                                </div>
                                <div class="rating-area text-center">
                                    <h3>{{ item.vote }}</h3>
                                    <div class="stars">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- ### Pagination Area ### -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination mt-100">
                            <li class="page-item active"><a class="page-link" href="#">01</a></li>
                            <li class="page-item"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Game Review Area End ##### -->
{% endblock %}

templates/gamingnews/home.html
{% extends "index.html" %}
{% load staticfiles %}


{% block content %}
    {% block monthpick %}
        <!-- ##### Monthly Picks Area Start ##### -->
        <section class="monthly-picks-area section-padding-100 bg-pattern">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="left-right-pattern"></div>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Title -->
                        <h2 class="section-title mb-70 wow fadeInUp" data-wow-delay="100ms">This Month’s Pick</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <ul class="nav nav-tabs wow fadeInUp" data-wow-delay="300ms" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="popular-tab" data-toggle="tab" href="#popular" role="tab" aria-controls="popular" aria-selected="true">Popular</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="latest-tab" data-toggle="tab" href="#latest" role="tab" aria-controls="latest" aria-selected="false">Latest</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="editor-tab" data-toggle="tab" href="#editor" role="tab" aria-controls="editor" aria-selected="false">Editor’s Pick</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="tab-content wow fadeInUp" data-wow-delay="500ms" id="myTabContent">
                <div class="tab-pane fade show active" id="popular" role="tabpanel" aria-labelledby="popular-tab">
                    <!-- Popular Games Slideshow -->
                    <div class="popular-games-slideshow owl-carousel">

                        <!-- Single Games -->
                        {% for item in games %}
                        <div class="single-games-slide">
                            <img src="{{ item.image.url }}" style="width: 238px;height: 403px;" alt="Cannot find this image"/>
                            <div class="slide-text">
                                <a href="#" class="game-title">{{ item.name }}</a>
                                <div class="meta-data">
                                    <a href="#">User: {{ item.vote}}</a>
                                    <a href="#">{{ item.category }}</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}




                    </div>
                </div>
                <div class="tab-pane fade" id="latest" role="tabpanel" aria-labelledby="latest-tab">
                    <!-- Latest Games Slideshow -->
                    <div class="latest-games-slideshow owl-carousel">

                        <!-- Single Games -->
                        <div class="single-games-slide">
                            <img src="/img/bg-img/50.jpg" alt="">
                            <div class="slide-text">
                                <a href="#" class="game-title">Grand Theft Auto V</a>
                                <div class="meta-data">
                                    <a href="#">User: 9.1/10</a>
                                    <a href="#">Action</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="tab-pane fade" id="editor" role="tabpanel" aria-labelledby="editor-tab">
                    <!-- Editor Games Slideshow -->
                    <div class="editor-games-slideshow owl-carousel">

                        <!-- Single Games -->
                        <div class="single-games-slide">
                            <img src="/img/bg-img/50.jpg" alt="">
                            <div class="slide-text">
                                <a href="#" class="game-title">Grand Theft Auto V</a>
                                <div class="meta-data">
                                    <a href="#">User: 9.1/10</a>
                                    <a href="#">Action</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </section>
        <!-- ##### Monthly Picks Area End ##### -->
    {% endblock %}

    {% block articles %}
        <!-- ##### Articles Area Start ##### -->
        <section class="latest-articles-area section-padding-100-0 bg-img bg-pattern bg-fixed" style="background-image: url({% static 'css_js' %}/img/bg-img/5.jpg);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-6 col-lg-4">
                        <!-- Title -->
                        <h2 class="section-title mb-70 wow fadeInUp" data-wow-delay="100ms">This week’s deal</h2>

                        <!-- Single Widget Area -->
                        <div class="single-widget-area add-widget wow fadeInUp" data-wow-delay="300ms">
                            <a href="#"><img src="{% static 'css_js' %}/img/bg-img/add.png" alt=""></a>
                            <!-- Side Img -->
                            <img src="{% static 'css_js' %}/img/bg-img/side-img.png" class="side-img" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ##### Articles Area End ##### -->

        {% endblock %}
{% endblock %}

templates/gamingnews/single-game-review.html
{% extends "index.html" %}
{% load staticfiles %}
{% load humanize %}
{% block title %}
    <title>Game Detail</title>
{% endblock %}

{% block content %}
    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area bg-img bg-overlay"
         style="background-image: url({% static 'css_js' %}/img/bg-img/27.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Game Review</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Single Game Review Area Start ##### -->
    <section class="single-game-review-area section-padding-100">
        <div class="container">
            <div class="row align-items-center">
                <!-- *** Review Area *** -->
                <div class="col-12 col-md-6">
                    <div class="single-game-review-area style-2 mt-70">
                        {% if game %}
                            <div class="game-content">
                                <span class="game-tag">{{ game.category }}</span>
                                <a href="single-game-review.html" class="game-title">{{ game.name }}</a>
                                <div class="game-meta">
                                    <a href="#" class="game-date">{{ game.updated_at }}</a>
                                    <a href="#" class="game-price">{{ game.price }}$</a>
                                </div>
                                <p>{{ game.description }}</p>
                                <!-- Download & Rating Area -->
                                <div class="download-rating-area">
                                    <div class="download-area">
                                        <a href="#"><img src="img/core-img/app-store.png" alt=""></a>
                                        <a href="#"><img src="img/core-img/google-play.png" alt=""></a>
                                    </div>
                                    <div class="rating-area mt-30">
                                        <h3>{{ game.vote }}</h3>
                                        <div class="stars">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>

                <!-- *** Barfiller Area *** -->
                <div class="col-12 col-md-6">
                    <div class="egames-barfiller">
                        <img src="{{ game.image.url }}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <form action="{% url 'cart:cart_add' game.id %}" method="post" style="
    margin-left: 13%;
">
            {% csrf_token %}
            <div class="form-inline">
                <label style="
    margin-bottom: 10px;
">
                    <input type="radio" name="Th_don_gia"
                           value="{{ game.price }}" checked>
                    Price: {{ game.price|intcomma }}$
                </label>
            </div>
            <div class="post_text form-inline">
                <input type="number" name="quantity" class="form-control" style="width: 90px; text-align:center"
                       id="id_quantity">

                <input type="submit" value="Add to cart" class="btn btn-success" style="
    margin-left: 2%;
">
            </div>
        </form>
    </section>

    <!-- ##### Single Game Review Area End ##### -->
{% endblock %}
{% block footer %}

{% endblock %}